<?php

/**
 * @file
 * Primary module hooks for ONLYOFFICE DocSpace Connector module.
 */

/**
 * Copyright (c) Ascensio System SIA 2023.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\onlyoffice_docspace\OnlyofficeAppConfig;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function onlyoffice_docspace_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.onlyoffice':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The ONLYOFFICE connector allows users to edit office documents, spreadsheets, and presentations in the Media module from Drupal using ONLYOFFICE Docs packaged as Document Server. Users are able to collaborate on documents in real-time and preview files on public pages.') . '</p>';

      $output .= '<h3>' . t('Installation and configuration') . '</h3>';
      $output .= '<p>' . t('Explore how to install and configure the ONLYOFFICE connector for Drupal on the <a href=":onlyoffice-drupal">official project page</a>.', [':onlyoffice-drupal' => 'https://github.com/ONLYOFFICE/onlyoffice-drupal']) . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function onlyoffice_docspace_theme($existing, $type, $theme, $path) {
  return [
    'onlyoffice_docspace_page' => [
      'variables' => [
      ],
      'template' => 'onlyoffice-docspace-page'
    ],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function onlyoffice_docspace_library_info_build() {

  $options = \Drupal::config('onlyoffice.settings');

  if ($doc_server_url = $options->get('doc_server_url')) {
    $api_url = $doc_server_url . OnlyofficeAppConfig::getDocServiceApiUrl();
    return [
      'onlyoffice.api' => [
        'js' => [
          $api_url => [],
        ],
      ],
    ];
  }
}
