<?php

/**
 * @file
 * Primary module hooks for ONLYOFFICE DocSpace Connector module.
 */

/**
 * Copyright (c) Ascensio System SIA 2023.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\onlyoffice_docspace\Plugin\Field\FieldType\OODSPItem;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;

/**
 * Implements hook_help().
 */
function onlyoffice_docspace_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.onlyoffice':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The ONLYOFFICE connector allows users to edit office documents, spreadsheets, and presentations in the Media module from Drupal using ONLYOFFICE Docs packaged as Document Server. Users are able to collaborate on documents in real-time and preview files on public pages.') . '</p>';

      $output .= '<h3>' . t('Installation and configuration') . '</h3>';
      $output .= '<p>' . t('Explore how to install and configure the ONLYOFFICE connector for Drupal on the <a href=":onlyoffice-drupal">official project page</a>.', [':onlyoffice-drupal' => 'https://github.com/ONLYOFFICE/onlyoffice-drupal']) . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function onlyoffice_docspace_theme($existing, $type, $theme, $path) {
  return [
    'onlyoffice_docspace_page' => [
      'variables' => [],
      'template' => 'onlyoffice-docspace-page',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_delete() for user entities.
 */
function onlyoffice_docspace_user_delete($account) {
  \Drupal::database()->delete('users_docspace')
    ->condition('uid', $account->id())
    ->execute();
}

/**
 * Implements hook_entity_update().
 */
function onlyoffice_docspace_entity_update(EntityInterface $entity) {
  if (!($entity instanceof FieldableEntityInterface)) {
    return;
  }

  $userStorage = \Drupal::service('entity_type.manager')->getStorage('user');
  $account = $userStorage->load(0);
  
  if (!$entity->isPublished() || !$account->hasPermission('access content')) {
    return;
  }
  
  $rooms_id = [];
  $files_id = [];

  $oodsp_item_fields = _onlyoffice_docspace_get_oodsp_item_fields($entity);

  foreach ($oodsp_item_fields as $oodsp_item_field) {
    $field_items = $entity->get($oodsp_item_field);
    foreach ($field_items as $field_item) {
      if (!empty($field_item->target_id)) {
        if ($field_item->type === 'manager') {
          $rooms_id[] = $field_item->target_id;
        }

        if ($field_item->type === 'manager') {
          $files_id[] = $field_item->target_id;
        }
      }
    }
  }

  $files_id = array_unique($files_id);

  foreach ($files_id as $file_id) {
    $responseFileInfo = \Drupal::service('onlyoffice_docspace.request_manager')->getFileInfo($file_id);

    if (!$responseFileInfo['error']) {
      $folder_id = $responseFileInfo['data']['folderId'];

      $responseFolderInfo = \Drupal::service('onlyoffice_docspace.request_manager')->getFolderInfo($folder_id);

      if (!$responseFolderInfo['error']) {
        $room_id = $responseFolderInfo['data']['pathParts'][1];
        $rooms_id[] = $room_id;
      } else {
        \Drupal::messenger()->addError(print_r($responseShareRoom, true)); // ToDo: error 
      }
    } else {
      \Drupal::messenger()->addError(print_r($responseShareRoom, true)); // ToDo: error 
    }
  }

  $rooms_id = array_unique( $rooms_id );

  foreach ($rooms_id as $room_id) {
    $responseShareRoom = \Drupal::service('onlyoffice_docspace.request_manager')->shareRoomPublicUser($room_id);
    if ($responseShareRoom['error']) {
      \Drupal::messenger()->addError(print_r($responseShareRoom, true)); // ToDo: error 
    }
    \Drupal::messenger()->addStatus(print_r($responseShareRoom, true)); //ToDo: success 
  }
}

function _onlyoffice_docspace_get_oodsp_item_fields(FieldableEntityInterface $entity) {
  $field_definitions = $entity->getFieldDefinitions();
  if (empty($field_definitions)) {
    return [];
  }

  $field_type_manager = \Drupal::service('plugin.manager.field.field_type');
  return array_keys(array_filter($field_definitions, function (FieldDefinitionInterface $definition) use ($field_type_manager) {
    $type = $definition->getType();
    $plugin_class = $field_type_manager->getPluginClass($type);
    return is_subclass_of($plugin_class, OODSPItem::class) || $plugin_class === OODSPItem::class;
  }));
}
